trigger:
  branches:
    include:
      - main

pool:
  name: Infra-Runners-pool

variables:
  TF_VERSION: '1.14.0'
  AZURE_SERVICE_CONNECTION: 'WebAppServiceConnection'

steps:
  - task: TerraformInstaller@1
    displayName: 'Install Terraform CLI'
    inputs:
      terraformVersion: 'latest'

  - task: TerraformTaskV4@4
    displayName: 'Terraform Init'
    inputs:
      provider: 'azurerm'
      command: 'init'
     
  - task: TerraformTaskV4@4
    displayName: 'Terraform Plan'
    inputs:
      provider: 'azurerm'
      command: 'plan'
     

  - task: TerraformTaskV4@4
    displayName: 'Terraform Apply'
    inputs:
      provider: 'azurerm'
      command: 'apply'
    
      args: '-auto-approve'
