trigger:
  branches:
    include:
      - main

pool:
  name: Infra-Runners-pool

variables:
  TF_VERSION: '1.14.0'
  AZURE_SERVICE_CONNECTION: 'WebAppServiceConnection'

steps:
  - task: TerraformInstaller@1
    displayName: 'Install Terraform CLI'
    inputs:
      terraformVersion: $(TF_VERSION)

  - task: TerraformTaskV4@4
    displayName: 'Terraform Init'
    inputs:
      provider: 'azurerm'
      command: 'init'
      environmentServiceNameAzureRM: $(AZURE_SERVICE_CONNECTION)

  - task: TerraformTaskV4@4
    displayName: 'Terraform Plan'
    inputs:
      provider: 'azurerm'
      command: 'plan'
      environmentServiceNameAzureRM: $(AZURE_SERVICE_CONNECTION)

  - task: TerraformTaskV4@4
    displayName: 'Terraform Apply'
    inputs:
      provider: 'azurerm'
      command: 'apply'
      environmentServiceNameAzureRM: $(AZURE_SERVICE_CONNECTION)
      args: '-auto-approve'
